spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/my-db-test;mode=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    open-in-view: true

    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

  sql:
    init:
      mode: always
